### ISSUE TITLE
Github action build一直失败

### ISSUE THREAD

**Issue by Hingwing** [Vu1nT0tal/yarb#25]
改了mail 的 secrets 和 secrets_receiver，构建的时候一直提示smtp login失败（授权码应该没问题）
![1704098410393](https://github.com/Vu1nT0tal/yarb/assets/24378715/37d19164-56cf-40f0-8174-41cb2643cf26)

**Comment by firmianay** [comment]
但是这个好像确实是授权码的问题？

**Comment by Hingwing** [comment]
![image](https://github.com/Vu1nT0tal/yarb/assets/24378715/1bc16a10-2282-4bc6-b61e-05a01d76bc6b)
跟您确认一下，是配置这3项？
